name: Package Application with Pyinstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: src

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AutoClicker
          path: src/dist/windows
